### ISSUE TITLE
`xcrun swift --version` may not terminate

### ISSUE THREAD

**Issue by 0xced** [segiddins/xcinvoke#3]
If you have an old version of Xcode 4.6.3 lying around ([some](http://twitter.com/pyby85/status/694147348725895168) [people](http://twitter.com/0xced/status/694150915968868352) do), xcinvoke will not terminate because it somehow becomes stuck in a loop:

![xcrun swift --version](https://cloud.githubusercontent.com/assets/51363/12733443/2dc2f92a-c93b-11e5-8d8e-1fe5db1cbd06.gif)

Running /full/path/to/xcrun (that you can get with `xcrun -f xcrun`) works fine and outputs the following (expected) error for Xcode 4.6.3:

```
xcrun: error: unable to find utility "swift", not a developer tool or in PATH
```

**Comment by segiddins** [comment]
Can you see if https://github.com/segiddins/xcinvoke/pull/4  fixes this issue?

**Comment by 0xced** [comment]
How can I test this? I encountered this issue when running [jazzy](http://github.com/realm/jazzy) but running `rake spec` on the `v0.2.0` tag doesn’t expose this issue:

```
xcinvoke[master] $ rake spec

--------------------------------------------------------------------------------
Running Unit Tests
--------------------------------------------------------------------------------

bundle exec bacon spec/xcode_spec.rb

XCInvoke::Xcode
  #initialize
  selected
  .each



0 specifications (0 requirements), 0 failures, 0 errors

--------------------------------------------------------------------------------
Checking Style Conformance
--------------------------------------------------------------------------------

Running RuboCop...
Inspecting 7 files
.......

7 files inspected, no offenses detected
```

So passing tests on the `seg-xcrun-f` branch won’t guarantee that the issue is fixed.

**Comment by segiddins** [comment]
Yeah, I know. Can you put this branch of xcinvoke in your gemfile?

**Comment by 0xced** [comment]
Here’s what I tried:

```
xcinvoke[seg-xcrun-f] $ bundle install
Resolving dependencies...
Using rake 10.4.2
Using addressable 2.3.8
Using ast 2.0.0
Using parser 2.2.2.6
Using astrolabe 1.3.1
Using bacon 1.2.0
Using bundler 1.10.6
Using safe_yaml 1.0.4
Using crack 0.4.2
Using liferaft 0.0.4
Using metaclass 0.0.4
Using mocha 1.1.0
Using mocha-on-bacon 0.2.2
Using powerpack 0.1.1
Using prettybacon 0.0.2
Using rainbow 2.0.0
Using ruby-progressbar 1.7.5
Using rubocop 0.32.1
Using webmock 1.21.0
Using xcinvoke 0.2.0 from source at .
Bundle complete! 9 Gemfile dependencies, 20 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
0xced@Mabolo xcinvoke[seg-xcrun-f] $ bundle exec ./bin/console 
irb(main):001:0> XCInvoke::Xcode.find_swift_version("2.1.1")
^CIRB::Abort: abort then interrupt!
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:289:in `call'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:289:in `value'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:289:in `block in capture3'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:99:in `popen3'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open3.rb:279:in `capture3'
    from /Users/0xced/Projects/xcinvoke/lib/xcinvoke/xcode.rb:84:in `xcrun'
    from /Users/0xced/Projects/xcinvoke/lib/xcinvoke/xcode.rb:117:in `swift_info'
    from /Users/0xced/Projects/xcinvoke/lib/xcinvoke/xcode.rb:57:in `swift_version'
    from /Users/0xced/Projects/xcinvoke/lib/xcinvoke/xcode.rb:53:in `block in find_swift_version'
    from /Users/0xced/Projects/xcinvoke/lib/xcinvoke/xcode.rb:44:in `each'
    from /Users/0xced/Projects/xcinvoke/lib/xcinvoke/xcode.rb:44:in `each'
    from /Users/0xced/Projects/xcinvoke/lib/xcinvoke/xcode.rb:53:in `select'
    from /Users/0xced/Projects/xcinvoke/lib/xcinvoke/xcode.rb:53:in `find_swift_version'
    from (irb):1
    from ./bin/console:11:in `<main>'
```

I’m not sure that the `xcinvoke` is the local one of the `seg-xcrun-f` branch by doing so though.

**Comment by segiddins** [comment]
So that's with it using the full path ¯_(ツ)_/¯

**Comment by 0xced** [comment]
OK, I found the issue: don’t pass the environment when running `xcrun -f xcrun`. By using a more recent version of xcrun everything works fine:

```
0xced@Mabolo xcinvoke[seg-xcrun-f] $ bundle exec ./bin/console 
irb(main):001:0> XCInvoke::Xcode.find_swift_version("2.1.1")
=> #<XCInvoke::Xcode:0x007f937a81c418 @developer_dir=#<Pathname:/Applications/Xcode72.app/Contents/Developer>, @xcrun_path="/Applications/Xcode72.app/Contents/Developer/usr/bin/xcrun">
```

``` patch
diff --git a/lib/xcinvoke/xcode.rb b/lib/xcinvoke/xcode.rb
index 1b32469..b1dd6d3 100644
--- a/lib/xcinvoke/xcode.rb
+++ b/lib/xcinvoke/xcode.rb
@@ -74,7 +74,7 @@ module XCInvoke

     def xcrun(cmd, env: {}, err: false)
       env = env.merge(as_env)
-      @xcrun_path ||= Open3.capture2(env, 'xcrun', '-f', 'xcrun').first.strip
+      @xcrun_path ||= Open3.capture2('xcrun', '-f', 'xcrun').first.strip
       cmd = [@xcrun_path] + cmd
       case err
       when :merge
```
