### ISSUE TITLE
xcrun can't find itself

### ISSUE THREAD

**Issue by davidahouse** [segiddins/xcinvoke#6]
Looks like the Xcode 8 GM doesn't include a version of `xcrun` inside the Xcode.app/Contents/Developer/usr/bin folder. While Xcode 7 did include it. So the code in this gem that executes `xcrun -f xcrun` will fail if using Xcode 8. Would this path ever NOT be /usr/bin/xcrun?

**Comment by pcantrell** [comment]
Also getting this on my install. Here’s what the stack trace looks like:

```
xcrun: error: unable to find utility "xcrun", not a developer tool or in PATH
/Users/paul/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory -  (Errno::ENOENT)
    from /Users/paul/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
    from /Users/paul/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open3.rb:95:in `popen3'
    from /Users/paul/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open3.rb:258:in `capture3'
    from /Users/paul/.rvm/gems/ruby-2.3.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:86:in `xcrun'
    from /Users/paul/.rvm/gems/ruby-2.3.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:119:in `swift_info'
    from /Users/paul/.rvm/gems/ruby-2.3.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:57:in `swift_version'
    from /Users/paul/.rvm/gems/ruby-2.3.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:53:in `block in find_swift_version'
    from /Users/paul/.rvm/gems/ruby-2.3.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:44:in `each'
    from /Users/paul/.rvm/gems/ruby-2.3.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:44:in `each'
    from /Users/paul/.rvm/gems/ruby-2.3.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:53:in `select'
    from /Users/paul/.rvm/gems/ruby-2.3.0/gems/xcinvoke-0.2.1/lib/xcinvoke/xcode.rb:53:in `find_swift_version'
```

**Comment by pcantrell** [comment]
[This line](https://github.com/segiddins/xcinvoke/blob/master/lib/xcinvoke/xcode.rb#L79) is the culprit:

```
  @xcrun_path ||= Open3.capture2('xcrun', '-f', 'xcrun').first.strip
```

@segiddins: I see in the commit history that you made extra effort to run `xcrun` with a full path. What was the rationale for that? It still runs as just `xcrun` the first time to discover its own location, so it’s still relaying on `PATH` … so … ?? Testing with jazzy, change the above to this works just fine:

```
  @xcrun_path ||= 'xcrun'
```

**Comment by segiddins** [comment]
It fixed things with Xcode 5 iirc
